language: ruby
cache:
- bundler
services:
  - postgresql
  - memcached
addons:
    postgresql: '9.6'

before_script:
- psql -c 'create database bookly_development;' -U postgres
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: rails-bookly
  on:
    repo: AhmadIbrahiim/bookly
