language: ruby
cache:
- bundler
before_script:
- docker-compose up -d
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: rails-bookly
  on:
    repo: AhmadIbrahiim/bookly
